### ISSUE TITLE
Error: secret "metadata-db-secrets" not found

### ISSUE THREAD

**Issue by pdmack** [kubeflow/metadata#204] opened 2020-01-10 18:12 UTC
/kind bug

kfctl 1.0 rc0

These all fail to start due to the secret not being created.

```
NAME                                                           READY     STATUS                       RESTARTS   AGE
metadata-db-dc799559d-hmmcv                                    0/1       CreateContainerConfigError   0          27m
metadata-deployment-5bbd74644c-jpgkg                           0/1       CreateContainerConfigError   0          27m
metadata-grpc-deployment-6b5454dbbb-6k8vg                      0/1       CreateContainerConfigError   0          27m
```

**Comment by biggedi** [comment] 2020-01-14 09:55
Adding the secret generator to ./kustomize/metadata/kustomization.yaml works around this bug:

`
secretGenerator:
- name: metadata-db-secrets
  env: overlays/db/secrets.env
`

**Comment by biggedi** [comment] 2020-01-21 08:07
This might be caused by kubeflow/kfctl#156

**Comment by Altair3** [comment] 2020-01-24 19:02
running into this as well. Where exactly in ~/kustomization.yaml do I add those lines?

**Comment by biggedi** [comment] 2020-01-27 07:27
You can add it anywhere in the file ./kustomize/metadata/kustomization.yaml.

Note that the kustomize folder needs to be generated first, as described in https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/#alternatively-set-up-your-configuration-for-later-deployment

**Comment by marcindulak** [comment] 2020-02-01 02:53
> Adding the secret generator to ./kustomize/metadata/kustomization.yaml works around this bug:
> 
> ```
> - name: metadata-db-secrets
>   env: overlays/db/secrets.env
> ```

Didn't work for me (followed by `kustomize build kustomize/metadata | kubectl apply -f -`).

Adding the following in `kustomize/metadata/kustomization.yaml` resulted in creation the `metadata-db-secrets` secret.

```
secretGenerator:
- behavior: unspecified
  name: metadata-db-secrets
  env: overlays/db/secrets.env
```

Note that recent kustomize (I'm using `Version: {KustomizeVersion:3.0.0 GitCommit:e0bac6ad192f33d993f11206e24f6cda1d04c4ec BuildDate:2019-07-03T18:21:24Z GoOs:linux GoArch:amd64}`) has troubles with `env` https://github.com/kubeflow/metadata/issues/202

**Comment by marcindulak** [comment] 2020-02-04 23:46
No more CreateContainerConfigError as in the original report with kustomize_3.0.0 https://github.com/kubeflow/kfctl/releases/tag/v1.0-rc.3 and https://github.com/kubeflow/manifests/blob/bf518c8392f377c47911b09a1dbeac3dbb051d9e/kfdef/kfctl_k8s_istio.v1.0.0.yaml on k8s v1.15.7.

**Comment by zhenghuiwang** [comment] 2020-02-24 22:57
Duplicate of https://github.com/kubeflow/kfctl/issues/156

Fixed by in kfclt v1rc3 release.

**Closed by zhenghuiwang** 2020-02-24 22:57 UTC
Labels: kind/bug

**Comment by stomplee** [comment] 2020-02-28 18:10
I have this same issue with the latest AWS kfdef and kfctl v1.0-0-g94c35cf.  Had to use the fix above to resolve.
